### PR TITLE
Switch to Python 3 (only)

### PR DESCRIPTION
**Pull request by ntninja**
This repo is pretty outdated and obviously unmaintained atm.

The below changes (while not fixing all of #26) are IMHO an important step towards proper Python 3 support and where done by @dheatovwil.

In an effort to update this codebase for the requirements of a future `py-ipfs` implementation, I would therefor kindly ask for this GitHub organization (and ideally also the corresponding [PyPI packages](https://pypi.org/search/?q=datastore)) to be handed over to more active members of the community attempting to build a usable version of `py-ipfs`.

I'd suggest the following people to take over these projects:

  * @AliabbasMerchant: Has already helped out in several IPFS Python related projects and continues to provide good code when he has time.
  * @alexander255 (me): While I'm myself not active in *building* `py-ipfs` I ended up being its project coordinator for now (a job I like quite a bit more, than actual coding anyways), I'd mostly use my position to add other team members and necessary/sensible.
  * @dheatovwil (if he's still around): Initiated the work on this repo half a year ago, I'll have to see if he's still around / interested in this through.

I know this may come somewhat unexpected, but since you literally have withdrawn from almost all development for almost 3 years @jbenet, I thought confronting you like this may be more effective than weaseling around. 😉

### CODE REVIEW

**Comment by brondsem** [comment]
It would be nice to see new maintenance of the datastore library and python 3 support.

I've tested this updated version a little bit on python 3, and got an error using the filesystem backend:

```
  File "datastore/core/serialize.py", line 200, in put
    self.child_datastore.put(key, value)
  File "datastore/filesystem/__init__.py", line 184, in put
    self._write_object(path, value)
  File "datastore/filesystem/__init__.py", line 140, in _write_object
    f.write(value)
TypeError: write() argument must be str, not bytes
```

It can be fixed by changing the open() calls to be binary:
```
with open(path, 'wb') as f:
...

with open(path, 'rb') as f:
```

**Comment by dheatovwil** [comment]
I was quite inactive in the past few months, but I guess I'm back, will need some time to keep up since I'm quite out of the loop actually.

My time is kinda limited now, but AFAIK the primary goal is all about resolving compatibility issue with the dependents, which I think I still can handle.

Just feel free to inform me if this is actually something much bigger than I thought, I'll see what I can do.

**Comment by dheatovwil** [comment]
> 
> 
> It would be nice to see new maintenance of the datastore library and python 3 support.
> 
> I've tested this updated version a little bit on python 3, and got an error using the filesystem backend:
> 
> ```
>   File "datastore/core/serialize.py", line 200, in put
>     self.child_datastore.put(key, value)
>   File "datastore/filesystem/__init__.py", line 184, in put
>     self._write_object(path, value)
>   File "datastore/filesystem/__init__.py", line 140, in _write_object
>     f.write(value)
> TypeError: write() argument must be str, not bytes
> ```
> 
> It can be fixed by changing the open() calls to be binary:
> 
> ```
> with open(path, 'wb') as f:
> ...
> 
> with open(path, 'rb') as f:
> ```

It seems that `str` is expected internally.  For now I've changed it to r/w in byte mode, and convert to byte when writing if `str` is given, but I will look deeper into this issue.

**Comment by ntninja** [comment]
Taking a quick look I'd definitely think that values should be binary strings only (encoding left up the application), while key names should be Unicode-strings (internally encoded to UTF-8 or UTF-16) if required by the given backend.

**Comment by AliabbasMerchant** [comment]
Hello  
@alexander255 Thank you for tagging me!  
I would definitely like to contribute.  
I will take some time to go through the repo, but after that, I will definitely contribute.  
@dheatovwil  or @alexander255  (or someone else for that matter), It would be better if you assign me some task (preferably something not so urgent, so that I can first go through properly and then start off).

(PS: I have been working on something quite similar to the concept of "datastore-agnostic, allowing datastores to be swapped seamlessly", so I think I can properly fit in here. You can check it out here: https://github.com/spaceuptech/ (Especially the python API and the main repo, "space-cloud")

**Comment by AliabbasMerchant** [comment]
@alexander255 @dheatovwil  
Seeing that this is quite a small project, why don't we just make a new copy of it, directly intended for Python 3?

I think I can do it in approx a month

**Comment by dheatovwil** [comment]
> 
> 
> @alexander255 @dheatovwil
> Seeing that this is quite a small project, why don't we just make a new copy of it, directly intended for Python 3?
> 
> I think I can do it in approx a month

I have no problem with that.  I can provide _some_ help if you need.

**Comment by ntninja** [comment]
Your're right of course! I was hoping to continue this project as-is, but I guess it's not happening so let's yield to reality here. :slightly_smiling_face: 
I've created an “official” fork here: https://github.com/ipfs/py-datastore 
Please send all PRs to that repository instead, so that we may actually get some work done.

I also forked off https://github.com/ipfs/py-datastore.leveldb which will need to read `go-ipfs` management data; the other backends do not look useful at this time.

**Comment by ntninja** [comment]
@AliabbasMerchant: I've missed your PS unfortunately. Since that thing is written in Go we cannot replace the `datastore` API itself with this. It may be suitable as a backend through.

**Pull request closed without merging**
